[build]
  publish = "frontend/build"
  command = "cd frontend && npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_BACKEND_URL = "https://your-backend-api.herokuapp.com"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-api.herokuapp.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
